#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and special messages for the 4th, 9th, and 17th iterations

i=1
while [ $i -le 20 ]
do
    echo $i
    case $i in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    ((i++))
done
